spring:
  application:
    name: HELLO-CONFIG-CLIENT
  profiles:
    active: ${ACTIVE_PROFILE}
  cloud:
    config:
      enabled: false
      profile: ${ACTIVE_PROFILE}
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: app_user
    password: app_user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false